spring:
  datasource:
    username: postgres
    password: ghbdtn
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
  mvc:
    view:
      prefix: /page/
      suffix: .jsp
  jpa:
    #    hibernate:
    #      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    enabled: true
    locations[0]: classpath:/db/migration
