hibernate:
  connection:
    username: postgres
    password: ghbdtn
    url: jdbc:postgresql://localhost:5432/library
    driver_class: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQL95Dialect
spring:
  mvc:
    view:
      prefix: /page/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop