create table if not exists users
(
    id         integer generated by default as identity,
    login      varchar(255) not null
        constraint unique_login unique,
    password   varchar(255) not null,
    role       varchar(255) not null,
    created    date         not null,
    updated    date         not null,
    is_deleted boolean      not null,
    primary key (id)
);

create table if not exists books
(
    id            integer generated by default as identity,
    author        varchar(255) not null,
    title         varchar(255) not null,
    year          integer      not null,
    created       date         not null,
    updated       date         not null,
    is_available  boolean      not null,
    is_deleted    boolean      not null,
    date_of_issue date,
    primary key (id)
);

create table if not exists users_books
(
    id      integer generated by default as identity,
    user_id integer not null,
    book_id integer not null,
    constraint fk_user_id foreign key (user_id) references users (id),
    constraint fk_book_id foreign key (book_id) references books (id),
    primary key (id)
);